export const scaleFactor = 4;

export const dialogueData = {
    GitHub: 'Check out my github repositories. My user name is <a href="https://github.com/maltsandcino">@maltsandcino</a>. Most of my work is in private / comapany Repos, but there are a few open and interesting things here.',
    welcome: "Welcome to Tom Harrison's 8Bit-inspired Portfolio. Learn more about me and my projects by going to the objects in the room. Or, directly visit my <a href='https://github.com/maltsandcino'>github</a>, <a href='https://www.linkedin.com/in/tharrisoncs/'>LinkedIn</a>, <a href='https://portfolios-smoky.vercel.app/'>PortfoliOS</a>, or view my <a href='https://github.com/maltsandcino/8BitCV/blob/main/public/Thomas%20Harrison%20Resume.pdf'>resume</a> on Github.",
    Contact: "Get in touch with me at <a mailto='thomas.jh@gmail.com'>thomasjh@gmail.com</a> or on <a href='https://www.linkedin.com/in/tharrisoncs/'>LinkedIn</a>",
    CV: "Check out my current <a href='github.com/maltsandcino/8BitCV/blob/main/public/Thomas%20Harrison%20Resume.pdf'>resume</a>. Maybe we can add to it together! Currently I work as a developer at a SAAS company in Belgium.",
    Education: "I have a master's degree from <a href='https://niagara.edu'>Niagara</a>, and a B.A. from <a href='https://mun.ca'>Memorial</a>, plus about 15 Math and CS courses at <a href='iu.de'>IU</a>, <a href='https://pll.harvard.edu/'>Harvard's</a> CS50W, AI, X, and fun things like <a href='https://www.nand2tetris.org/'>NAND2Tetris</a>. I use Python, Javascript, (relevant frameworks thereof), HTML, CSS, XML, JSON, YAML on a daily basis. I like DSA, ML, webdev, OOP, and pointers.",
    Projects: "Some of my recent projects have been: An Inter-API Microservice, Assembly Language to Machine Language Parser (which writes functional code for a VML designed virtual CPU), ML-Sentiment Analysis and Sarcasm API, SAAS Maintenance/Dev",
}